### ISSUE TITLE
Traceback (most recent call last):

### ISSUE THREAD

**Issue by nqsd123** [kessil/quizXue#18]
(venv) C:\Users\Administrator\venv\Scripts>python main.py --device huawei_p20
Traceback (most recent call last):
  File "main.py", line 98, in <module>
    cfg.read('./default.ini')
  File "H:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\config
parser.py", line 696, in read
    self._read(fp, filename)
  File "H:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\config
parser.py", line 1014, in _read
    for lineno, line in enumerate(fp, start=1):
UnicodeDecodeError: 'gbk' codec can't decode byte 0xa1 in position 1332: illegal
 multibyte sequence

请帮我看下什么问题，原来用老版本没有问题

**Comment by kesisour** [comment]
> (venv) C:\Users\Administrator\venv\Scripts>python main.py --device huawei_p20
> Traceback (most recent call last):
> File "main.py", line 98, in 
> cfg.read('./default.ini')
> File "H:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\config
> parser.py", line 696, in read
> self._read(fp, filename)
> File "H:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\config
> parser.py", line 1014, in _read
> for lineno, line in enumerate(fp, start=1):
> UnicodeDecodeError: 'gbk' codec can't decode byte 0xa1 in position 1332: illegal
> multibyte sequence
> 
> 请帮我看下什么问题，原来用老版本没有问题

你好，我也是这种情况，你是怎么解决的？

**Comment by kessil** [comment]
cfg.read(‘./default.ini')改为cfg.read('./default.ini', encoding='utf-8')
cfg.read(‘./user.ini')改为cfg.read('./user.ini', encoding='utf-8')
