### ISSUE TITLE
 File "daily.py", line 265, in <module>

### ISSUE THREAD

**Issue by nqsd123** [kessil/quizXue#19]
(venv) C:\Users\Administrator\venv\Scripts>python daily.py
running init func...
running start func...
running enter func...
1135 KB/s (9882 bytes in 0.008s)
Traceback (most recent call last):
  File "daily.py", line 265, in <module>
    daily.start()
  File "daily.py", line 246, in start
    self.enter()
  File "daily.py", line 105, in enter
    self.pos_home = self._get_bounds(self.home_bounds)[0]
IndexError: list index out of range
用MUMU每日答题出现这个问题，求大神帮忙

**Comment by zz803abc** [comment]
me too
