### ISSUE TITLE
脚本不能使用，出现错误

### ISSUE THREAD

**Issue by squirrelmedia** [kessil/quizXue#26]
**- 手机连接adb显示错误**
```
C:\Users\Administrator\Desktop\quizXue-master>python main.py --device huawei_p20
1135 KB/s (6811 bytes in 0.005s)
Traceback (most recent call last):
  File "main.py", line 109, in <module>
    start(device, count_question, filename, database_uri, delay_seconds, user_agent)
  File "main.py", line 52, in start
    question = Bank.from_xml(device)
  File "C:\Users\Administrator\Desktop\quizXue-master\model.py", line 49, in from_xml
    cfg.read('./default.ini')
  File "C:\python\lib\configparser.py", line 696, in read
    self._read(fp, filename)
  File "C:\python\lib\configparser.py", line 1014, in _read
    for lineno, line in enumerate(fp, start=1):
UnicodeDecodeError: 'gbk' codec can't decode byte 0xa1 in position 1332: illegal multibyte sequence
```
**- 运行mumu显示错误**
```
C:\Users\Administrator\Desktop\quizXue-master>python daily.py
running init func...
running start func...
running enter func...
1361 KB/s (6811 bytes in 0.004s)
Traceback (most recent call last):
  File "daily.py", line 265, in <module>
    daily.start()
  File "daily.py", line 246, in start
    self.enter()
  File "daily.py", line 105, in enter
    self.pos_home = self._get_bounds(self.home_bounds)[0]
IndexError: list index out of range
```
**恳请及时解决**

**Comment by hushiyan01** [comment]
第一个编码有问题，你在那个提示错误的文件夹下的configparser.py 文件的695行改成这个
open(filename,encoding="UTF-8")
![image](https://user-images.githubusercontent.com/47495160/62419165-a0ce1000-b6ac-11e9-8782-17ee21b46650.png)

第二个list 索引超范围是因为你没有按照要求放起始界面，起始界面放到学习强国主页面

**Comment by squirrelmedia** [comment]
> 第一个编码有问题，你在那个提示错误的文件夹下的configparser.py文件的695行改成这个
> open（filename，encoding =“UTF-8”）
> ![图片](https://user-images.githubusercontent.com/47495160/62419165-a0ce1000-b6ac-11e9-8782-17ee21b46650.png)
> 
> 第二个列表索引超范围是因为你没有按照要求放起始界面，起始界面放到学习强国主页面

十分感谢您的解决方法，但是使用手机连接adb的方法更改完后依然出现错误

```
C:\Users\Administrator\Desktop\quizXue-master>python main.py --device huawei_p20
1111 KB/s (6811 bytes in 0.005s)
Traceback (most recent call last):
  File "main.py", line 109, in <module>
    start(device, count_question, filename, database_uri, delay_seconds, user_agent)
  File "main.py", line 52, in start
    question = Bank.from_xml(device)
  File "C:\Users\Administrator\Desktop\quizXue-master\model.py", line 55, in from_xml
    xml_question = root.xpath(cfg.get(device, 'question'))[-1]
IndexError: list index out of range
```

**Comment by kessil** [comment]
configparse.py是python内置库，强烈不建议修改！
对于这个bug，只要将daily.py和main.py做如下修改：
cfg.read('./default.ini', encoding='utf-8')
cfg.read('./user.ini', encoding='utf-8')
其他问题可能是平台更新了UI布局造成，请静候下一个版本，项目重构中，感谢支持

**Comment by squirrelmedia** [comment]
> configparse.py是python内置库，强烈不建议修改！
> 对于这个bug，只要将daily.py和main.py做如下修改：
> cfg.read（'。/ default.ini'，encoding ='utf-8'）
> cfg.read（'./ user.ini'，encoding ='utf-8'）
> 其他问题可能是平台更新了UI布局造成，请静候下一个版本，项目重构中，感谢支持

十分感谢您的解答，静等下一个版本
