### ISSUE TITLE
最近更新的版本用不了，能出个详细视频教程吗

### ISSUE THREAD

**Issue by wo900316** [kessil/quizXue#29]
最近更新的版本用不了，能出个详细视频教程吗

**Comment by kessil** [comment]
试试最新的dev分支吧，没什么异常的话将合并到master。readme说明了使用方法

**Comment by 20057842** [comment]
dev和master都按照readme步骤，但提示一个错误。

master
D:\XX\quizXue-master>python -m xuexi -a -c -d -v
Traceback (most recent call last):
  File "C:\Users\I3\AppData\Local\Programs\Python\Python37-32\lib\runpy.py", lin
e 183, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "C:\Users\I3\AppData\Local\Programs\Python\Python37-32\lib\runpy.py", lin
e 142, in _get_module_details
    return _get_module_details(pkg_main_name, error)
  File "C:\Users\I3\AppData\Local\Programs\Python\Python37-32\lib\runpy.py", lin
e 109, in _get_module_details
    __import__(pkg_name)
  File "D:\XX\quizXue-master\xuexi\__init__.py", line 19, in <module>
    logger = create_logger('xuexi', 'DEBUG')
  File "D:\XX\quizXue-master\xuexi\logs\__init__.py", line 42, in create_logger
    handler_common = logging.FileHandler(os.path.join(basedir, 'LOG', common_fil
ename), mode='a', encoding='utf-8')
  File "C:\Users\I3\AppData\Local\Programs\Python\Python37-32\lib\logging\__init
__.py", line 1087, in __init__
    StreamHandler.__init__(self, self._open())
  File "C:\Users\I3\AppData\Local\Programs\Python\Python37-32\lib\logging\__init
__.py", line 1116, in _open
    return open(self.baseFilename, self.mode, encoding=self.encoding)
FileNotFoundError: [Errno 2] No such file or directory: 'D:\\XX\\quizXue-master\
\xuexi\\logs\\LOG\\20190808.log'

dev

D:\XX\quizXue-dev>venv\scripts\python -m xuexi -a -c -d -v
Traceback (most recent call last):
  File "C:\Users\I3\AppData\Local\Programs\Python\Python37-32\lib\runpy.py", lin
e 183, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "C:\Users\I3\AppData\Local\Programs\Python\Python37-32\lib\runpy.py", lin
e 142, in _get_module_details
    return _get_module_details(pkg_main_name, error)
  File "C:\Users\I3\AppData\Local\Programs\Python\Python37-32\lib\runpy.py", lin
e 109, in _get_module_details
    __import__(pkg_name)
  File "D:\XX\quizXue-dev\xuexi\__init__.py", line 19, in <module>
    logger = create_logger('xuexi', 'DEBUG')
  File "D:\XX\quizXue-dev\xuexi\logs\__init__.py", line 42, in create_logger
    handler_common = logging.FileHandler(os.path.join(basedir, 'LOG', common_fil
ename), mode='a', encoding='utf-8')
  File "C:\Users\I3\AppData\Local\Programs\Python\Python37-32\lib\logging\__init
__.py", line 1087, in __init__
    StreamHandler.__init__(self, self._open())
  File "C:\Users\I3\AppData\Local\Programs\Python\Python37-32\lib\logging\__init
__.py", line 1116, in _open
    return open(self.baseFilename, self.mode, encoding=self.encoding)
FileNotFoundError: [Errno 2] No such file or directory: 'D:\\XX\\quizXue-dev\\xu
exi\\logs\\LOG\\20190808.log'

**Comment by 20057842** [comment]
另外旧版本是不是可以删除了（1.1、1.2），旧版本只能做每天答题，挑战答题提示错误MUMU模拟器（2.2.13.2），是不是要安装1.1的说明，安装百度或者谷歌OCR？

**Comment by kessil** [comment]
因为git不上传空文件夹，导致一个FileNotFoundError: [Errno 2] No such file or directory报错，已修复。直接拉取master

**Comment by 20057842** [comment]
真的可以了，厉害。非常感谢。。现在还有一个问题，MUMU多开APP但挂不了（错误代码最后）???求大神我的操作有没错？
以下是流程。
①https://github.com/kessil/quizXue》点击》Branch》选择master》Clone or download》下载解压2.0版本

②下载安装》MuMu模拟器2.2.12（现在官网直接下载的最新版为2.2.13）》分辨率设置默认最小864*540
CMD模拟器指令：
adb devices
adb kill-server   
adb start-server
adb connect 127.0.0.1:7555  (连接MUMU模拟器)
adb shell uiautomator dump /sdcard/ui.xml   （获取UIXML后怎么添加手机UI型号？不会求教）

③下载安装》Python 3.7.4》https://www.python.org/downloads/》安装的时候确保勾选》add Python ** to PATH
部署：忘记了，然后按照大神的教程》双击运行初次安装.bat

④下载解压》ADB 1.0.40（第①压缩包有）
部署：系统属性》环境变量》系统变量》新建变量》ANDROID_ADB_SERVER_PORT》值》5037（这步是默认端口5037被占用后更改为12345？）

⑤下载安装》ADB platform-tools》https://adb.clockworkmod.com/
部署：系统属性》环境变量》系统变量》找变量“path”编辑》输入“;D:\Program Files\ADB\platformtools\platform-tools”（PS:输入带“;”←这个，然后路径放哪里就设置哪里，然后把ADB 1.0.40覆盖进platform-tools，这步我有没做错？）

⑥下载模拟器后安装》学XQG V2.5.0.apk

⑦下载模拟器后安装》ADBKeyboard.apk（解决输入中文）（第①压缩包有）》模拟器设置默认输入法（为什么每次启动都要设置？有解决办法吗？直接删了自带的？求助）

完结？求大神我的操作有没错？


多开错误提示：
连接模拟器127.0.0.1:7555 成功
阅读文章功能正在实现中
视听学习功能正在实现中
Traceback (most recent call last):
  File "C:\Users\I3\AppData\Local\Programs\Python\Python37-32\lib\runpy.py", lin
e 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Users\I3\AppData\Local\Programs\Python\Python37-32\lib\runpy.py", lin
e 85, in _run_code
    exec(code, run_globals)
  File "D:\XX\quizXue-master\xuexi\__main__.py", line 41, in <module>
    app.start(args.article, args.video, args.daily, args.challenge)
  File "D:\XX\quizXue-master\xuexi\__init__.py", line 56, in start
    self._quiz_run(day, chg)
  File "D:\XX\quizXue-master\xuexi\__init__.py", line 47, in _quiz_run
    qApp.start(day, chg)
  File "D:\XX\quizXue-master\xuexi\quiz\__init__.py", line 62, in start
    self.ad.tap(self.mine)
  File "D:\XX\quizXue-master\xuexi\common\adble.py", line 117, in tap
    dx, dy = int(x.real), int(x.imag)
AttributeError: 'list' object has no attribute 'real'
断开模拟器127.0.0.1:7555 成功

**Comment by kessil** [comment]
没测试多开（mumu打开多个app？)
不用配置分辨率，不用添加手机型号
建议将学习app设置字体最小
程序启动会将输入法设为adbboardkey
程序退出前会将输入法恢复原默认输入法
你的这个报错，有无打开学习app并置于首页？

**Comment by 20057842** [comment]
谢谢大神！！mumu没有其他模拟器的多开功能，只有一个多开分身功能（原版正常，多开的就提示，是置于首页状态。

**Comment by wo900316** [comment]
不用MUMU模拟器，直接手机调试模式OK吗？

**Comment by PerhapSC** [comment]
> 谢谢大神！！mumu没有其他模拟器的多开功能，只有一个多开分身功能（原版正常，多开的就提示，是置于首页状态。

您好！请问为什么我的输入法始终没法再学xqg里输入文字啊...

**Comment by xiao3783** [comment]
点击初次安装，出现Python不是内部或者外部命令，请大神帮我下。谢谢啦

**Comment by kessil** [comment]
> 
> 
> 点击初次安装，出现Python不是内部或者外部命令，请大神帮我下。谢谢啦

你第一次安装python吧？请百度python添加环境变量吧
