### ISSUE TITLE
提交新增题目反馈(专用)

### ISSUE THREAD

**Issue by kessil** [kessil/quizXue#32]
有意反馈新增题目者请在这里提交。
首先确保配置文件中is_user=true，刷到新题存入数据库同时会在./xuexi/src/json/*.json保存一份副本，反馈新题只需上传该json文件，如下：
[daily.txt](https://github.com/kessil/quizXue/files/3477557/daily.txt)

**Comment by wmm1118** [comment]
'adb' 不是内部或外部命令，也不是可运行的程序
或批处理文件。
Traceback (most recent call last):
  File "D:\Python\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "D:\Python\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\www\Desktop\quizXue-master\quizXue-master\xuexi\__main__.py", line 40, in <module>
    app = App()
  File "C:\Users\www\Desktop\quizXue-master\quizXue-master\xuexi\__init__.py", line 35, in __init__
    cfg.getint(self.rules, 'port'))
  File "C:\Users\www\Desktop\quizXue-master\quizXue-master\xuexi\common\adble.py", line 26, in __init__
    self._connect()
  File "C:\Users\www\Desktop\quizXue-master\quizXue-master\xuexi\common\adble.py", line 35, in _connect
    if 0 == subprocess.check_call(f'adb connect {self.host}:{self.port}', shell=True, stdout=subprocess.PIPE):
  File "D:\Python\lib\subprocess.py", line 347, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'adb connect 127.0.0.1:7555' returned non-zero exit status 1.
Exception ignored in: <function App.__del__ at 0x02D9E390>
Traceback (most recent call last):
  File "C:\Users\www\Desktop\quizXue-master\quizXue-master\xuexi\__init__.py", line 61, in __del__
    self.ad.close()
AttributeError: 'App' object has no attribute 'ad'

**Comment by kessil** [comment]
不要在此回复其他无关消息

**Comment by 17837697** [comment]
[
    {
        "id": 3049,
        "catagory": "挑战题",
        "content": "良渚古城遗址位于浙江省        ，地处中国东南沿海长江流域天目山东麓河网纵横的平原地带。",
        "options": "杭州市 宁波市 嘉兴市 绍兴市",
        "answer": "A",
        "note": ""
    },
    {
        "id": null,
        "catagory": "挑战题",
        "content": "下列典故与项羽有关的是        。",
        "options": "隔岸观火 暗渡陈仓 背水一战 破釜沉舟",
        "answer": "",
        "note": "A"
    },
    {
        "id": null,
        "catagory": "挑战题",
        "content": "唐代诗人白居易的诗句：“绿蚁新醅酒，红泥小火炉”，中“绿蚁”指的是        。",
        "options": "绿色的蚂蚁 酒上浮起的绿色泡沫 茶水 酒器",
        "answer": "",
        "note": "A"
    }
]

[
    {
        "id": 3046,
        "catagory": "填空题",
        "content": "流行性感冒简称流感，是由流感病毒感染引起的急性呼吸道传染病，也是一种传染性强、传播速度快的疾病。如果得了流感应尽量避免外出，在不用退热药的情况下退热至少  小时后方可外出。",
        "options": "1",
        "answer": "24",
        "note": "流感是由流感病毒感染引起的急性呼吸道传染病，传染性强，患者应尽量在家休息、避免外出，在不用退热药的情况下退热至少24小时后方可外出，确需外出时务必戴好口罩。"
    },
    {
        "id": 3047,
        "catagory": "单选题",
        "content": "“中华开国五千年，神州轩辕自古传。创造指南车，平定蚩尤乱，世界文明，唯有我先”是以下哪位伟人所作？        （出题单位：西部网 推荐单位：陕西学习平台）",
        "options": "",
        "answer": "B",
        "note": "轩辕黄帝，是传说中原各民族的共同祖先。中华民族五千年的光辉灿烂的文明和历史主要就是从黄帝开国算起。孙中山曾写过“中华开国五千年，神州轩辕自古传，创造指南车，平定蚩尤乱，世界文明，唯有我先”这样的诗句。"
    },
    {
        "id": 3048,
        "catagory": "填空题",
        "content": "2019年3月3日至13日，中国人民政治协商会议第十三届全国委员会第二次会议在北京召开。会议强调，今年是中华人民共和国成立70周年。站在新的历史起点上，要深刻理解在中国共产党领导下新中国70年历史性变革中所蕴藏的内在逻辑，把握历史性成就背后的中国特色社会主义道路、理论、制度、    ，坚定信心决心，增强行动自觉，在接续奋斗中创造新的辉煌。（出题单位：新疆兵团第十三师职业技术学校 推荐单位：新疆兵团学习平台）",
        "options": "1",
        "answer": "文化优势",
        "note": "中国人民政治协商会议第十三届全国委员会第二次会议强调，站在新的历史起点上，要深刻理解在中国共产党领导下新中国70年历史性变革中所蕴藏的内在逻辑，把握历史性成就背后的中国特色社会主义道路、理论、制度、文化优势，坚定信心决心，增强行动自觉，在接续奋斗中创造新的辉煌。"
    },
    {
        "id": 3050,
        "catagory": "单选题",
        "content": "旅行社应当提示参加团队旅游的旅游者按照规定购买何种保险?         （出题单位：长沙市文化旅游广电局 推荐单位：湖南学习平台）",
        "options": "",
        "answer": "B",
        "note": "根据《中华人民共和国旅游法》第六十一条规定，旅行社应当提示参加团队旅游的旅游者按照规定投保人身意外伤害保险。"
    },
    {
        "id": 3051,
        "catagory": "填空题",
        "content": "新中国第一部彩色故事片是1956年由北京电影制片厂拍摄的《  》。",
        "options": "1",
        "answer": "祝福",
        "note": "1956年北京电影制片厂出品的电影《祝福》是新中国第一部彩色故事片。《祝福》凭借鲁迅原著的坚实基础，夏衍的成功改编，以及演员白杨、魏鹤龄深厚的表演功底，使它成为当时国内观众最喜爱的影片之一，并于1957年获得第10届卡罗维发利国际电影节的特别奖。"
    },
    {
        "id": 3052,
        "catagory": "填空题",
        "content": "          是我军加强党的领导和党的建设工作的首要任务。",
        "options": "1",
        "answer": "坚持党对军队绝对领导",
        "note": " "
    }
]

**Comment by squirrelmedia** [comment]
[daily.txt](https://github.com/kessil/AutoXue/files/3507923/daily.txt)

**Comment by coscyang** [comment]
阅读文章视听学习每日答题挑战答题[√]                                                           
当前设备 127.0.0.1:7555                                                                   
1381 KB/s (55256 bytes in 0.039s)                                                     
1322 KB/s (27767 bytes in 0.020s)                                                     
Traceback (most recent call last):                                                    
  File "F:\Miemie\xuexiqiangguo\Scripts\xuexi\common\adble.py", line 167, in tap      
    dx, dy = int(x.real), int(x.imag)                                                 
AttributeError: 'list' object has no attribute 'real'                                 
                                                                                      
During handling of the above exception, another exception occurred:                   
                                                                                      
Traceback (most recent call last):                                                    
  File "D:\Work Tools\work\python\lib\runpy.py", line 193, in _run_module_as_main     
    "__main__", mod_spec)                                                             
  File "D:\Work Tools\work\python\lib\runpy.py", line 85, in _run_code                
    exec(code, run_globals)                                                           
  File "F:\Miemie\xuexiqiangguo\Scripts\xuexi\__main__.py", line 41, in <module>      
    app.start(args.article, args.video, args.daily, args.challenge)                   
  File "F:\Miemie\xuexiqiangguo\Scripts\xuexi\__init__.py", line 62, in start         
    self._quiz_run(day, chg)                                                          
  File "F:\Miemie\xuexiqiangguo\Scripts\xuexi\__init__.py", line 57, in _quiz_run     
    qApp.start(day, chg)                                                              
  File "F:\Miemie\xuexiqiangguo\Scripts\xuexi\quiz\__init__.py", line 65, in start    
    self.ad.tap(pos)                                                                  
  File "F:\Miemie\xuexiqiangguo\Scripts\xuexi\common\adble.py", line 169, in tap      
    raise AttributeError(f'{x} 不是可点击的坐标')                                             
AttributeError: [] 不是可点击的坐标                                                           
断开模拟器127.0.0.1:62001 成功             

使用mumu模拟器，提示如下

**Comment by hydjq** [comment]
[challenge .txt](https://github.com/kessil/AutoXue/files/3527598/challenge.txt)
[daily.txt](https://github.com/kessil/AutoXue/files/3527599/daily.txt)

**Comment by hydjq** [comment]
[challenge .txt](https://github.com/kessil/AutoXue/files/3536360/challenge.txt)
[daily .txt](https://github.com/kessil/AutoXue/files/3536361/daily.txt)

**Comment by squirrelmedia** [comment]
[daily.txt](https://github.com/kessil/AutoXue/files/3536706/daily.txt)

**Comment by wsl5778036** [comment]
[daily.txt](https://github.com/kessil/AutoXue/files/3543596/daily.txt)

**Comment by wsl5778036** [comment]
[daily.txt](https://github.com/kessil/AutoXue/files/3543601/daily.txt)

**Comment by td-date** [comment]
[daily.txt](https://github.com/kessil/AutoXue/files/3553659/daily.txt)

**Comment by hydjq** [comment]
[daily .txt](https://github.com/kessil/AutoXue/files/3683726/daily.txt)
[challenge.txt](https://github.com/kessil/AutoXue/files/3683727/challenge.txt)

**Comment by td-date** [comment]
[challenge.txt](https://github.com/kessil/AutoXue/files/3759475/challenge.txt)
[daily.txt](https://github.com/kessil/AutoXue/files/3759477/daily.txt)
挑战可能有错题.

**Comment by td-date** [comment]
https://github.com/kessil/AutoXue/issues/121#issuecomment-546769473
