### ISSUE TITLE
ui.xml里已经看不到题目了，解析失败

### ISSUE THREAD

**Issue by ponyjoy** [kessil/quizXue#4]
界面的layout可能修改了，ui.xml里已经看不到题目了，解析失败
Traceback (most recent call last):
  File "main.py", line 82, in <module>
    run(session)
  File "main.py", line 50, in run
    question = Bank.from_xml(filename)
  File "G:\quizXue\model.py", line 48, in from_xml
    xml_question = root.xpath(Config.XPATH_QUESTION)[0]
IndexError: list index out of range

**Comment by kessil** [comment]
重新运行即可
