### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by zzzzzqf** [kessil/quizXue#8]
C:\Users\xxx\Desktop\quizXue-master\quizXue-master>C:\Users\xxx\AppData\Local\Programs\Python\Python37\python.exe main.py
UI hierchary dumped to: /sdcard/ui.xml
/sdcard/ui.xml: 1 file pulled. 2.4 MB/s (12571 bytes in 0.005s)
Traceback (most recent call last):
  File "main.py", line 86, in <module>
    run(session, 35)
  File "main.py", line 52, in run
    question = Bank.from_xml(filename)
  File "C:\Users\xxx\Desktop\quizXue-master\quizXue-master\model.py", line 48, in from_xml
    xml_question = root.xpath(Config.XPATH_QUESTION)[0]
IndexError: list index out of range

<?xml version='1.0' encoding='UTF-8' standalone='yes' ?><hierarchy rotation="3"><node index="0" text="" resource-id="" class="android.widget.FrameLayout" package="cn.xuexi.android" content-desc="" checkable="false" checked="false" clickable="false" enabled="true" focusable="false" focused="false" scrollable="false" long-clickable="false" password="false" selected="false" bounds="[0,0][1080,1920]"><node index="0" text="" resource-id="" class="android.widget.LinearLayout" package="cn.xuexi.android" content-desc="" checkable="false" checked="false" clickable="false" enabled="true" focusable="false" focused="false" scrollable="false" long-clickable="false" password="false" selected="false" bounds="[0,0][1080,1920]"><node index="0" text="" resource-id="" class="android.widget.FrameLayout" package="cn.xuexi.android" content-desc="" checkable="false" checked="false" clickable="false" enabled="true" focusable="false" focused="false" scrollable="false" long-clickable="false" password="false" selected="false" bounds="[0,0][1080,1920]"><node index="0" text="" resource-id="cn.xuexi.android:id/action_bar_root" class="android.widget.LinearLayout" package="cn.xuexi.android" content-desc="" checkable="false" checked="false" clickable="false" enabled="true" focusable="false" focused="false" scrollable="false" long-clickable="false" password="false" selected="false" bounds="[0,0][1080,1920]"><node index="0" text="" resource-id="android:id/content" class="android.widget.FrameLayout" package="cn.xuexi.android" content-desc="" checkable="false" checked="false" clickable="false" enabled="true" focusable="false" focused="false" scrollable="false" long-clickable="false" password="false" selected="false" bounds="[0,0][1080,1920]"><node index="0" text="" resource-id="cn.xuexi.android:id/ui_common_base_ui_activity_root" class="android.widget.LinearLayout" package="cn.xuexi.android" content-desc="" checkable="false" checked="false" clickable="false" enabled="true" focusable="false" focused="false" scrollable="false" long-clickable="false" password="false" selected="false" bounds="[0,0][1080,1920]"><node index="0" text="" resource-id="cn.xuexi.android:id/ui_common_base_ui_activity_status_bar_placeholder" class="android.widget.FrameLayout" package="cn.xuexi.android" content-desc="" checkable="false" checked="false" clickable="false" enabled="true" focusable="false" focused="false" scrollable="false" long-clickable="false" password="false" selected="false" bounds="[0,0][1080,48]" /><node index="1" text="" resource-id="cn.xuexi.android:id/ui_common_base_ui_activity_content" class="android.widget.FrameLayout" package="cn.xuexi.android" content-desc="" checkable="false" checked="false" clickable="false" enabled="true" focusable="false" focused="false" scrollable="false" long-clickable="false" password="false" selected="false" bounds="[0,48][1080,1920]"><node index="0" text="" resource-id="cn.xuexi.android:id/content" class="android.widget.RelativeLayout" package="cn.xuexi.android" content-desc="" checkable="false" checked="false" clickable="false" enabled="true" focusable="false" focused="false" scrollable="false" long-clickable="false" password="false" selected="false" bounds="[0,48][1080,1920]"><node index="0" text="" resource-id="cn.xuexi.android:id/container" class="android.widget.FrameLayout" package="cn.xuexi.android" content-desc="" checkable="false" checked="false" clickable="false" enabled="true" focusable="false" focused="false" scrollable="false" long-clickable="false" password="false" selected="false" bounds="[0,48][1080,1920]"><node index="0" text="" resource-id="cn.xuexi.android:id/drawer_layout" class="android.support.v4.widget.DrawerLayout" package="cn.xuexi.android" content-desc="" checkable="false" checked="false" clickable="false" enabled="true" focusable="false" focused="false" scrollable="false" long-clickable="false" password="false" selected="false" bounds="[0,48][1080,1920]"><node index="0" text="" resource-id="cn.xuexi.android:id/main" class="android.widget.FrameLayout" package="cn.xuexi.android" content-desc="" checkable="false" checked="false" clickable="false" enabled="true" focusable="false" focused="false" scrollable="false" long-clickable="false" password="false" selected="false" bounds="[0,48][1080,1920]"><node index="0" text="" resource-id="cn.xuexi.android:id/webview_root" class="android.widget.RelativeLayout" package="cn.xuexi.android" content-desc="" checkable="false" checked="false" clickable="false" enabled="true" focusable="false" focused="false" scrollable="false" long-clickable="false" password="false" selected="false" bounds="[0,48][1080,1920]"><node index="0" text="" resource-id="cn.xuexi.android:id/fragment_container" class="android.widget.FrameLayout" package="cn.xuexi.android" content-desc="" checkable="false" checked="false" clickable="false" enabled="true" focusable="false" focused="false" scrollable="false" long-clickable="false" password="false" selected="false" bounds="[0,48][1080,1920]"><node index="0" text="" resource-id="" class="android.view.ViewGroup" package="cn.xuexi.android" content-desc="" checkable="false" checked="false" clickable="false" enabled="false" focusable="false" focused="false" scrollable="false" long-clickable="false" password="false" selected="false" bounds="[0,48][1080,1920]"><node index="0" text="" resource-id="cn.xuexi.android:id/webview_frame_layout" class="android.widget.RelativeLayout" package="cn.xuexi.android" content-desc="" checkable="false" checked="false" clickable="false" enabled="true" focusable="false" focused="false" scrollable="false" long-clickable="false" password="false" selected="false" bounds="[0,48][1080,1920]"><node index="0" text="" resource-id="cn.xuexi.android:id/webview_frame" class="android.widget.RelativeLayout" package="cn.xuexi.android" content-desc="" checkable="false" checked="false" clickable="false" enabled="true" focusable="false" focused="false" scrollable="false" long-clickable="false" password="false" selected="false" bounds="[0,48][1080,1920]"><node index="0" text="" resource-id="" class="com.uc.webview.export.WebView" package="cn.xuexi.android" content-desc="" checkable="false" checked="false" clickable="false" enabled="true" focusable="true" focused="true" scrollable="false" long-clickable="true" password="false" selected="false" bounds="[0,48][1080,1920]"><node index="0" text="" resource-id="" class="android.webkit.WebView" package="cn.xuexi.android" content-desc="" checkable="false" checked="false" clickable="false" enabled="true" focusable="false" focused="false" scrollable="false" long-clickable="false" password="false" selected="false" bounds="[0,48][1080,1920]"><node index="0" text="" resource-id="" class="android.webkit.WebView" package="cn.xuexi.android" content-desc="" checkable="false" checked="false" clickable="false" enabled="true" focusable="true" focused="true" scrollable="true" long-clickable="false" password="false" selected="false" bounds="[0,48][1080,1920]"><node index="0" text="" resource-id="" class="android.view.View" package="cn.xuexi.android" content-desc="" checkable="false" checked="false" clickable="true" enabled="true" focusable="false" focused="false" scrollable="false" long-clickable="false" password="false" selected="false" bounds="[36,140][236,194]" /><node index="1" text="" resource-id="" class="android.view.View" package="cn.xuexi.android" content-desc="" checkable="false" checked="false" clickable="false" enabled="true" focusable="false" focused="false" scrollable="false" long-clickable="false" password="false" selected="false" bounds="[478,242][602,372]" /><node index="2" text="" resource-id="" class="android.view.View" package="cn.xuexi.android" content-desc="南齐医药学家        的《本草经集注》将人文原则的“三品”分类法改为依药物自然来源和属性的分类法，开辟了本草学的新理论体系。（出题单位：山东科技报社 推荐单位：山东学习平台）" checkable="false" checked="false" clickable="true" enabled="true" focusable="false" focused="false" scrollable="false" long-clickable="false" password="false" selected="false" bounds="[76,408][1004,616]" /><node index="3" text="" resource-id="" class="android.widget.ListView" package="cn.xuexi.android" content-desc="" checkable="false" checked="false" clickable="false" enabled="true" focusable="false" focused="false" scrollable="false" long-clickable="false" password="false" selected="false" bounds="[76,716][1004,1240]"><node index="0" text="" resource-id="" class="android.view.View" package="cn.xuexi.android" content-desc="" checkable="false" checked="false" clickable="false" enabled="true" focusable="false" focused="false" scrollable="false" long-clickable="false" password="false" selected="false" bounds="[76,716][1004,832]"><node NAF="true" index="0" text="" resource-id="" class="android.widget.RadioButton" package="cn.xuexi.android" content-desc="" checkable="true" checked="false" clickable="true" enabled="true" focusable="true" focused="false" scrollable="false" long-clickable="false" password="false" selected="false" bounds="[76,716][108,748]" /><node index="1" text="" resource-id="" class="android.view.View" package="cn.xuexi.android" content-desc="李时珍" checkable="false" checked="false" clickable="true" enabled="true" focusable="false" focused="false" scrollable="false" long-clickable="false" password="false" selected="false" bounds="[76,716][1004,832]" /></node><node index="1" text="" resource-id="" class="android.view.View" package="cn.xuexi.android" content-desc="" checkable="false" checked="false" clickable="false" enabled="true" focusable="false" focused="false" scrollable="false" long-clickable="false" password="false" selected="false" bounds="[76,852][1004,968]"><node NAF="true" index="0" text="" resource-id="" class="android.widget.RadioButton" package="cn.xuexi.android" content-desc="" checkable="true" checked="false" clickable="true" enabled="true" focusable="true" focused="false" scrollable="false" long-clickable="false" password="false" selected="false" bounds="[76,852][108,884]" /><node index="1" text="" resource-id="" class="android.view.View" package="cn.xuexi.android" content-desc="陶弘景" checkable="false" checked="false" clickable="true" enabled="true" focusable="false" focused="false" scrollable="false" long-clickable="false" password="false" selected="false" bounds="[76,852][1004,968]" /></node><node index="2" text="" resource-id="" class="android.view.View" package="cn.xuexi.android" content-desc="" checkable="false" checked="false" clickable="false" enabled="true" focusable="false" focused="false" scrollable="false" long-clickable="false" password="false" selected="false" bounds="[76,988][1004,1104]"><node NAF="true" index="0" text="" resource-id="" class="android.widget.RadioButton" package="cn.xuexi.android" content-desc="" checkable="true" checked="false" clickable="true" enabled="true" focusable="true" focused="false" scrollable="false" long-clickable="false" password="false" selected="false" bounds="[76,988][108,1020]" /><node index="1" text="" resource-id="" class="android.view.View" package="cn.xuexi.android" content-desc="孙思邈" checkable="false" checked="false" clickable="true" enabled="true" focusable="false" focused="false" scrollable="false" long-clickable="false" password="false" selected="false" bounds="[76,988][1004,1104]" /></node><node index="3" text="" resource-id="" class="android.view.View" package="cn.xuexi.android" content-desc="" checkable="false" checked="false" clickable="false" enabled="true" focusable="false" focused="false" scrollable="false" long-clickable="false" password="false" selected="false" bounds="[76,1124][1004,1240]"><node NAF="true" index="0" text="" resource-id="" class="android.widget.RadioButton" package="cn.xuexi.android" content-desc="" checkable="true" checked="false" clickable="true" enabled="true" focusable="true" focused="false" scrollable="false" long-clickable="false" password="false" selected="false" bounds="[76,1124][108,1156]" /><node index="1" text="" resource-id="" class="android.view.View" package="cn.xuexi.android" content-desc="王叔和" checkable="false" checked="false" clickable="true" enabled="true" focusable="false" focused="false" scrollable="false" long-clickable="false" password="false" selected="false" bounds="[76,1124][1004,1240]" /></node></node></node></node></node></node></node></node></node></node></node></node></node></node></node></node></node></node></node></node></node></hierarchy>

**Comment by zzzzzqf** [comment]
ui.xml在这里
[ui.docx](https://github.com/kessil/quizXue/files/3385503/ui.docx)

**Comment by kessil** [comment]
> 
> 
> ui.xml在这里
> [ui.docx](https://github.com/kessil/quizXue/files/3385503/ui.docx)

请问你的ADB版本号是多少？ui.xml结构不一致，需要改动xpath规则。

**Comment by enuff** [comment]
> > ui.xml在这里
> > [ui.docx](https://github.com/kessil/quizXue/files/3385503/ui.docx)
> 
> 请问你的ADB版本号是多少？ui.xml结构不一致，需要改动的XPath规则。

提示同样的问题，adb版本1.0.36，分辨率是540,960

**Comment by nqsd123** [comment]
我也出现了这个问题，请问怎么解决的呢
